# Generated by Django 3.2.12 on 2022-11-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20221024_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes'),
        ),
    ]
