# Generated by Django 3.2.12 on 2022-11-27 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_paciente_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia_clinica',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cod_postal',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='img',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='lugar_nacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telf_fijo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telf_movil',
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='apellidos',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='ci',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='cod_postal',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='direccion',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes'),
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='lugar_nacimiento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.medico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='municipio',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='observaciones',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='provincia',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='sexo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.sexo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='telf_fijo',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='telf_movil',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
