# Generated by Django 3.2.12 on 2022-11-27 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20221127_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='situacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.formulario'),
            preserve_default=False,
        ),
    ]
