# Generated by Django 3.2.12 on 2022-11-27 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20221127_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='situacion',
        ),
        migrations.AddField(
            model_name='formulario',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.paciente'),
            preserve_default=False,
        ),
    ]
